### ISSUE TITLE
AssertionError: slim model only used in tensorflow 1.x

### ISSUE THREAD

**Issue by glucasol** [intel/neural-compressor#849]
Hi everyone,

I am trying to run the example 7 ([Hello-World Example](https://github.com/intel/neural-compressor/tree/master/examples/helloworld/tf_example7)), with a custom model trained using Anomalib's repo ([Anomalib](https://github.com/openvinotoolkit/anomalib)). So I just changed the model path to my own model, like this:

`from neural_compressor.config import PostTrainingQuantConfig
from neural_compressor.data import DataLoader
from neural_compressor.data import Datasets

dataset = Datasets('tensorflow')['dummy'](shape=(1, 224, 224, 3))
dataloader = DataLoader(framework='tensorflow', dataset=dataset)

from neural_compressor.quantization import fit
config = PostTrainingQuantConfig()
q_model = fit(
    model="./model_train3.ckpt",
    conf=config,
    calib_dataloader=dataloader,
    eval_dataloader=dataloader)`

**It always retuns this error:** 

`AssertionError                            Traceback (most recent call last)
[/tmp/ipykernel_30247/2647671713.py](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_30247/2647671713.py) in 
      8 from neural_compressor.quantization import fit
      9 config = PostTrainingQuantConfig()
---> 10 q_model = fit(
     11     model="[./model_train3.ckpt](https://file+.vscode-resource.vscode-cdn.net/home/gabrieloliveira/Documents/POCs/Dexco/model_train3.ckpt)",
     12     conf=config,

[~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py](https://file+.vscode-resource.vscode-cdn.net/home/gabrieloliveira/Documents/POCs/Dexco/~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py) in fit(model, conf, calib_dataloader, calib_func, eval_func, eval_dataloader, eval_metric, **kwargs)
    485     if eval_metric is not None:
    486         quantizer.metric = eval_metric
--> 487     return quantizer()

[~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py](https://file+.vscode-resource.vscode-cdn.net/home/gabrieloliveira/Documents/POCs/Dexco/~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py) in __call__(self)
    155         For derived classes(Pruning, Quantization, etc.), an override function is required.
    156         """
--> 157         self.pre_proccess()
    158         results = self.execute()
    159         return results

[~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py](https://file+.vscode-resource.vscode-cdn.net/home/gabrieloliveira/Documents/POCs/Dexco/~/anaconda3/lib/python3.9/site-packages/neural_compressor/quantization.py) in pre_proccess(self)
    114             logger.info("Quantize model without tuning!")
    115 
--> 116         self.strategy = STRATEGIES[strategy](
...
--> 516     assert version1_lt_version2(tf.version.VERSION, '2.0.0'), 'slim model only used in tensorflow 1.x'
    517     from .nets_factory import TFSlimNetsFactory
    518     factory = TFSlimNetsFactory()

AssertionError: slim model only used in tensorflow 1.x`

Can anyone help me?

**Comment by NeoZhangJianyu** [comment]
@glucasol 
We will check and feedback as soon!

**Comment by NeoZhangJianyu** [comment]
@glucasol 
Looks like your model is tf-slim model on TF 2.x.
INC only supports slim on TF 1.x.

You could convert the model to keras format on TF 2.x.

Thank you!

**Comment by glucasol** [comment]
@NeoZhangJianyu Thanks for your answer!
I have converted the model to .onnx format and tried to run the same example and now the error is different. It appears that dimensions does not match, like shown below: 

`2023-05-04 11:05:50.175469: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-04 11:05:51.043055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-04 11:05:52 [WARNING] Force convert framework model to neural_compressor model.
2023-05-04 11:05:52 [INFO] Start auto tuning.
2023-05-04 11:05:53 [WARNING] The model is automatically detected as a non-NLP model. You can use 'domain' argument in 'PostTrainingQuantConfig' to overwrite it
2023-05-04 11:05:53 [WARNING] Graph optimization level is automatically set to ENABLE_BASIC. You can use 'recipe' argument in 'PostTrainingQuantConfig'to overwrite it
2023-05-04 11:05:54 [INFO] Adaptor has 4 recipes.
2023-05-04 11:05:54 [INFO] 0 recipes specified by user.
2023-05-04 11:05:54 [INFO] 3 recipes require future tuning.
2023-05-04 11:05:54 [INFO] *** Initialize auto tuning
2023-05-04 11:05:54 [INFO] Get FP32 model baseline.
2023-05-04 11:05:54 [ERROR] Unexpected exception InvalidArgument('[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices\n index: 1 Got: 224 Expected: 3\n index: 2 Got: 224 Expected: 256\n index: 3 Got: 3 Expected: 256\n Please fix either the inputs or the model.') happened during tuning.
Traceback (most recent call last):
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/quantization.py", line 132, in execute
    self.strategy.traverse()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/auto.py", line 101, in traverse
    super().traverse()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 591, in traverse
    self._eval_baseline()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 711, in _eval_baseline
    self.baseline = self._evaluate(self.model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 1285, in _evaluate
    val = self.objectives.evaluate(eval_func, model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/objective.py", line 397, in evaluate
    acc = eval_func(model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/utils/create_obj_from_config.py", line 162, in eval_func
    return adaptor.evaluate(model, dataloader, postprocess,
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/adaptor/onnxrt.py", line 1262, in evaluate
    eval_func(dataloader)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/adaptor/onnxrt.py", line 1236, in eval_func
    predictions = session.run(None, ort_inputs)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 201, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 1 Got: 224 Expected: 3
 index: 2 Got: 224 Expected: 256
 index: 3 Got: 3 Expected: 256
 Please fix either the inputs or the model.
2023-05-04 11:05:54 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.`

Do you have any idea how could I fix it?

Thanks for your help!

**Comment by lvliang-intel** [comment]
Hi @glucasol,

Please note the following mismatches:

index 1: Got 224, Expected 3
index 2: Got 224, Expected 256
index 3: Got 3, Expected 256

The shape (1, 224, 224, 3) of the dummy dataset you used does not match the model's input dimensions (1, 3, 256, 256). To resolve this issue, you need to change the shape of the dummy dataset to (1, 3, 256, 256).

Here is the updated code:

dataset = Datasets('tensorflow')['dummy'](shape=(1, 3, 256, 256))
dataloader = DataLoader(framework='tensorflow', dataset=dataset)

**Comment by glucasol** [comment]
Hi @lvliang-intel 
Thanks for your response.
I updated the code, and now it is returning another error:
````
2023-05-08 11:03:14.057930: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-08 11:03:14.707783: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-05-08 11:03:15 [WARNING] Force convert framework model to neural_compressor model.
2023-05-08 11:03:16 [INFO] Start auto tuning.
2023-05-08 11:03:16 [WARNING] The model is automatically detected as a non-NLP model. You can use 'domain' argument in 'PostTrainingQuantConfig' to overwrite it
2023-05-08 11:03:16 [WARNING] Graph optimization level is automatically set to ENABLE_BASIC. You can use 'recipe' argument in 'PostTrainingQuantConfig'to overwrite it
2023-05-08 11:03:17 [INFO] Adaptor has 4 recipes.
2023-05-08 11:03:17 [INFO] 0 recipes specified by user.
2023-05-08 11:03:17 [INFO] 3 recipes require future tuning.
2023-05-08 11:03:17 [INFO] *** Initialize auto tuning
2023-05-08 11:03:17 [INFO] Get FP32 model baseline.
2023-05-08 11:03:18 [ERROR] Unexpected exception AssertionError('labels batch size should same with preds') happened during tuning.
Traceback (most recent call last):
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/quantization.py", line 132, in execute
    self.strategy.traverse()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/auto.py", line 101, in traverse
    super().traverse()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 591, in traverse
    self._eval_baseline()
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 711, in _eval_baseline
    self.baseline = self._evaluate(self.model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/strategy/strategy.py", line 1285, in _evaluate
    val = self.objectives.evaluate(eval_func, model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/objective.py", line 397, in evaluate
    acc = eval_func(model)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/utils/create_obj_from_config.py", line 162, in eval_func
    return adaptor.evaluate(model, dataloader, postprocess,
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/adaptor/onnxrt.py", line 1262, in evaluate
    eval_func(dataloader)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/adaptor/onnxrt.py", line 1248, in eval_func
    metric.update(predictions, labels)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/metric/metric.py", line 998, in update
    preds, labels = _topk_shape_validate(preds, labels)
  File "/home/gabrieloliveira/.local/lib/python3.8/site-packages/neural_compressor/metric/metric.py", line 465, in _topk_shape_validate
    assert label_N == N, 'labels batch size should same with preds'
AssertionError: labels batch size should same with preds
2023-05-08 11:03:18 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
````

Can you help me?

Thanks!

**Comment by lvliang-intel** [comment]
Hi @glucasol,
It seems that the issue is still related to the dataset. Could you kindly provide instructions on how to train the model and convert it to the ONNX format? This will enable me to replicate the problem locally.

**Comment by lvliang-intel** [comment]
Hi @glucasol,

We discovered a calibration problem in ONNX, which has been resolved in pull request by https://github.com/intel/neural-compressor/pull/870. To test it, you can utilize the 'mengni/fix' branch. Please employ the below code for quantization. I have successfully applied quantization to the padim model. Kindly review the quantization outcome displayed below. If you have any other questions, please feel free to let us know.

![image](https://github.com/intel/neural-compressor/assets/104267837/5280f0b7-8fc5-4ac7-885e-8f027b42864b)

> from neural_compressor.config import PostTrainingQuantConfig
> from neural_compressor.data import DataLoader
> from neural_compressor.data import Datasets
> from neural_compressor.quantization import fit
> 
> def main():
> 
>     # Built-in dummy dataset
>     dataset = Datasets('onnxrt_qlinearops')['dummy'](shape=[(1, 3, 256, 256)], label=True)
>     # Built-in calibration dataloader and evaluation dataloader for Quantization.
>     dataloader = DataLoader(framework='onnxrt_qlinearops', dataset=dataset)
>     # Post Training Quantization Config
>     config = PostTrainingQuantConfig()
>     # Please modify the eval_func if you using the real dataset
>     def eval_func(model):
>         return 1
>     # Just call fit to do quantization.
>     q_model = fit(model="./model.onnx",
>                   conf=config,
>                   calib_dataloader=dataloader,
>                   eval_dataloader=dataloader,
>                   eval_func = eval_func
>                   )
>     q_model.save("./q_model.onnx")
> 
> if __name__ == "__main__":
>    main()

**Comment by glucasol** [comment]
Hi @lvliang-intel,

Thank You so much for your help!
I tested it and is working!

Thanks!
